import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link active" href="/">Home
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/">Features</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/">Pricing</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/">About</a>
                </li>
              </ul>
              <ul class="d-flex" wtx-context="5A1A6F1E-CF9E-4AFC-886E-19E79A3EABE1">
                <li className='nav-item'>
                  <a class="nav-link" href="/register">Register</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        {children}
        </body>
    </html>
  )
}
